version: '2'
services:
    harambot9k-mysql:
        container_name: harambot9k-mysql
        image: mysql:5.7.12
        # volumes:
        #     - ~/volumes/jhipster/Harambot9k/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=harambot9k
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
